hack/usoc22: Update missing items in session 01
unikraft/docs pull request #104
Opened 2022-08-29 16:07 UTC by eduardvintila

Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2022-10-21 02:09 UTC, razvand requested changes
Hi, @eduardvintila . Please make sure there is a blank line before and after each code block.

Remove `bash` as a snippet type for code block that use commands. We will only use it for scripts.

2022-10-21 07:13 UTC, RaduNichita requested changes

2022-10-21 07:13 UTC, RaduNichita commented on content/en/community/hackathons/sessions/baby-steps/content/Demos_00.-Manual-kraft-Installation.md
> +```bash
```suggestion
```
```

2022-10-21 07:13 UTC, RaduNichita commented on content/en/community/hackathons/sessions/baby-steps/content/Demos_00.-Manual-kraft-Installation.md
> +```bash
```suggestion
```
```

2022-10-21 07:18 UTC, RaduNichita requested changes
Check also the linter issues [1], please.

[1] https://github.com/eduardvintila/docs/actions/runs/2950165555/jobs/4714570245

2023-09-16 17:29 UTC, StefanJum commented
Outdated by the USoC23 sessions.

2023-09-16 17:29 UTC, closed without merging