feat: Update basic-app-porting session
unikraft/docs pull request #107
Opened 2022-09-01 15:42 UTC by gabrielmocanu

feat: Update basic-app-porting session

Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

2022-09-01 18:59 UTC, StefanJum requested changes
Some comments that I cannot add to the `files` section, since there were no changes to those files:

* [Here](https://github.com/unikraft/docs/blob/717dd24aeab1aa7feff3450411f8e599dedb1f64/content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Identifying-a-Candidate-Application.md?plain=1#L9), instead of `C/++-based` --> `C/C++-based`.
* I would add some example links [here](https://github.com/unikraft/docs/blob/717dd24aeab1aa7feff3450411f8e599dedb1f64/content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Identifying-a-Candidate-Application.md?plain=1#L15) to [app-python](https://github.com/unikraft/app-python3/), [app-lua](https://github.com/unikraft/app-lua), etc.
* Add `bash` for the code snippets [here](https://github.com/unikraft/docs/blob/717dd24aeab1aa7feff3450411f8e599dedb1f64/content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Using-Your-Library-in-a-Unikraft-Unikernel-Application.md?plain=1#L7).
* [This](https://github.com/unikraft/docs/blob/717dd24aeab1aa7feff3450411f8e599dedb1f64/content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Patching-the-Application.md?plain=1#L31) is outdated since now we have some stub implementation for `mmap` and a stub for `munmap`, so the patch should not be necessary, but I guess we can keep this patch and add a note, just to keep things simple but updated.
* [This](https://github.com/unikraft/docs/blob/717dd24aeab1aa7feff3450411f8e599dedb1f64/content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_01.-Port-%60libfortune%60-to-Unikraft.md?plain=1#L11-L33) should be updated, both the GitHub links, paths, and the Unikraft banner version.

2022-09-01 18:59 UTC, StefanJum commented on content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Creating-a-Boilerplate-Microlibrary-for-Your-Application.md
>  That is, when we eventually build the application, the Unikraft build system will understand where to get the source code files, which ones to compile and how, with respect to the rest of Unikraft's
```suggestion
That is, when we eventually build the application, the Unikraft build system will understand where to get the source code files from, which ones to compile and how, with respect to the rest of Unikraft's internals and other dependencies.
```

2022-09-01 18:59 UTC, StefanJum commented on content/en/community/hackathons/sessions/basic-app-porting/content/Overview_Providing-Build-Files.md
> +   Remember in [the Unikraft build lifecycle](#the-unikraft-build-lifecycle) that there is a step which occurs between fetching the remote original code and compiling it. This step (3), known as `pre
```suggestion
   Remember in [the Unikraft build lifecycle](community/hackathons/usoc22/basic-app-porting/#the-unikraft-build-lifecycle) that there is a step which occurs between fetching the remote original code and compiling it. This step (3), known as `prepare`, is used to make modifications to the origin code before it is compiled.
```

2022-09-01 18:59 UTC, StefanJum commented on content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_Support-Files.md
>  ```
```suggestion
```bash
```

2022-09-01 18:59 UTC, StefanJum commented on content/en/community/hackathons/sessions/basic-app-porting/content/Work-Items_Support-Files.md
>  ```
```suggestion
```bash
```

2022-09-06 23:18 UTC, gabrielmocanu commented
1. Done
3. Done
4. Done

2022-09-07 06:28 UTC, StefanJum commented
@gabrielmocanu it looks good now, besides the problem with the lib that you are working on and the quiz we will need to have.

2022-09-07 12:43 UTC, StefanJum approved these changes
Looks good now, we will update the work items in a later pr.
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-09-07 13:17 UTC, merged