docs/porting: Add patching an application section
unikraft/docs pull request #116
Opened 2022-09-10 15:24 UTC by StefanJum

For some reason it seems like the `patching` part of the `porting` section was missed when adding content from [`USoC'21` - basic app porting](https://usoc21.unikraft.org/docs/sessions/08-basic-app-porting/#patching-the-application).

Signed-off-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-09-24 11:00 UTC, eduardvintila approved these changes
The patching section is now visible. Thanks for this, @StefanJum.
Reviewed-by: Eduard Vintilă eduard.vintila47@gmail.com

2022-09-29 09:12 UTC, StefanJum commented
This will need rebasing once #126 #125 and #124 are merged, I added the commits from there to check the linter output.

2022-09-30 05:26 UTC, razvand requested changes
I think the `$` sign should be kept in front of commands to make a difference between the command and its output.

Also, my suggestion is to update the linter to not require the language name for triple backtick environments. `bash` should only be used for shell scripts, not for commands; if used for commands, the highlight engine will also consider the command output - which shouldn't be highlighted.

2022-09-30 05:26 UTC, razvand commented on content/en/docs/develop/porting.md
> +### Patching the application
```suggestion
### Patching the Application
```

2022-09-30 05:26 UTC, razvand commented on content/en/docs/develop/porting.md
> +   In this file, we are receiving a duplicate import of `<netinent/tcp.h>`, simply removing this import fixes it, so the patch addresses this issue.
```suggestion
   In this file, we are receiving a duplicate import of `<netinet/tcp.h>`, simply removing this import fixes it, so the patch addresses this issue.
```

2022-09-30 05:26 UTC, razvand commented on content/en/docs/develop/porting.md
> +   In this case, `iperf3`, used `mmap` simply to statically allocate a region of memory.
```suggestion
   In this case, `iperf3` used `mmap` simply to statically allocate a region of memory.
```

2022-09-30 05:26 UTC, razvand commented on content/en/docs/develop/porting.md
> +Note that providing patches are an unfortunate workaround to the inherent differences between Linux user space applications and libraries and unikernels.
```suggestion
Note that providing patches is an unfortunate workaround to the inherent differences between Linux user space applications and libraries and unikernels.
```

2022-10-21 01:38 UTC, razvand approved these changes
All good. Thanks, @StefanJum 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-10-21 01:39 UTC, merged