Add blogpost for Unikraft Hacktoberfest '22
unikraft/docs pull request #132
Opened 2022-10-09 13:06 UTC by RaduNichita

Signed-off-by: Radu Nichita <radunichita99@gmail.com>

2022-10-10 18:50 UTC, razvand requested changes
Thanks, @RaduNichita , see my comments.

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +### A new beginning
```suggestion
### And Another One
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +Last weekend, Unikraft hosted a community event for the `Hacktoberfest` series.
```suggestion
Last weekend, we hosted yet another Unikraft hackathon, part of [Hacktoberfest 2022](https://hacktoberfest.com/).
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +The event was held in a hybrid way: the newcomers and some familiar faces met physically at `University POLITEHNICA of Bucharest`, whereas the other folks joined remotely on the `monkey-business` cha
```suggestion
This was a hybrid event: the newcomers and some familiar faces met physically at University POLITEHNICA of Bucharest, whereas the other folks joined remotely on [the Unikraft Discord server](http://bit.ly/UnikraftDiscord).
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +### First steps
```suggestion
### First Steps
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +### Hardwork always pays off
```suggestion
### Hard work Always Pays Off
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +Afterwards, the participants dove deep into the chosen tasks.
```suggestion
Afterwards, the participants dove deep into the chosen tasks, from the [`Hackathons` project on GitHub](https://github.com/orgs/unikraft/projects/29).
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +Most of them started by running the ` application on top of Unikraft.
```suggestion
Most of them started by running adding new [static PIE Linux executables](https://github.com/unikraft/static-pie-apps) to be run on top of Unikraft in binary compatibility mode using the [ELF Loader](https://github.com/unikraft/run-app-elfloader).
```

2022-10-10 18:50 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +After a few hours of intense hacking, results were on the table: 3 applications were ported as `static-build-pie` for Unikraft!!
```suggestion
After a few hours of intense hacking, results were on the table: 3 applications were ported as static PIE apps for Unikraft!
And participants are working forward to port applications and submit PRs.
Another PRs was submitted the next day.
```

2022-10-10 19:19 UTC, mandrei12 requested changes
I think the idea is there but we can work on the language and present the event in a more suitable and welcoming manner.

2022-10-10 23:08 UTC, RaduNichita reviewed
Nice nitpicks, @mandrei12! Thanks for that. I left some minor comments and suggestions.

2022-10-10 23:08 UTC, RaduNichita commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +As tradition dictates if it's Saturday then it is definitely another hackathon we are proud to host at Unikraft. Even so, the last one was a bit special. How you ask? Well, as we previously announced
```suggestion
As tradition dictates, if it's Saturday then it is definitely another hackathon we are proud to host at Unikraft. Even so, the last one was a bit special. How you ask? Well, as we previously announced, we have been officially accepted to be part of the [Hacktoberfest 2022](https://hacktoberfest.com/).
```

2022-10-10 23:08 UTC, RaduNichita commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +In order to break the ice, our documentation community lead, [Stefan Jumărea](https://github.com/StefanJum), gave a introductory presentation. This aimed to present both unikernels and Unikraft to th
```suggestion
In order to break the ice, our documentation community lead, [Stefan Jumărea](https://github.com/StefanJum), gave an introductory presentation. This aimed to present both unikernels and Unikraft to the participants, introducing it to the newcomers and refreshing it for the veterans. Afterward, a short discussion about the challenges raised our participant's spirits. Onto krafting young padawans!
```

2022-10-10 23:08 UTC, RaduNichita commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +While begginings can sometimes be hard and unrewarding, this was not the case for our contestans. After a few hours the results were on the table: 3 applications were ported as static PIE apps for Un
```suggestion
While beginnings can sometimes be challenging and unrewarding, this was not the case for our contestants. After a few hours, the results were on the table: 3 applications were ported as static PIE apps for Unikraft.

2022-10-10 23:08 UTC, RaduNichita commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +A great start! But wait, there's more! The participants continued working on their porting and submited their PRs. To our surprise we even had some PRs submited the next day.
```suggestion
A great start! But wait, there's more! The participants continued working on their porting and submitted their PRs. To our surprise we even had some PRs submitted even the next day!.
```

2022-10-11 02:38 UTC, razvand commented
@RaduNichita , you can ignore the Linter issue, it's something to do with the image inclusion.

Please integrate the comments you did for @mandrei12 's contributions and use `Resolve conversation`. Squash commits into a single one. Then ask for a final review and, once done, we'll publish it.

2022-10-11 16:51 UTC, razvand requested changes
I like it. See my comments. Use one sentence per each line.

Then it will be OK.

2022-10-11 16:51 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +author = "Radu Nichita"
```suggestion
author = "Radu Nichita, Andrei Mutu"
```

2022-10-11 16:51 UTC, razvand commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +As tradition dictates, if it's Saturday then it is definitely another hackathon we are proud to host at Unikraft. Even so, the last one was a bit special. How you ask? Well, as we previously announce
```suggestion
As tradition dictates, if it's Saturday then it is definitely another hackathon we are proud to host at Unikraft.
Even so, the last one was a bit special.
How you ask?
Well, as we previously announced, we have been officially accepted to be part of the [Hacktoberfest 2022](https://hacktoberfest.com/).
```

2022-10-11 18:13 UTC, mandrei12 requested changes
Besides the typo it looks good.

2022-10-11 18:13 UTC, mandrei12 commented on content/en/blog/2022-10-08-unikraft-hacktoberfest.md
> +Afterward, a short discussion about the challenges raised our participant's spirits.
I think here is a typo. It should be `participants` without the apostrophe.

2022-10-11 18:51 UTC, mandrei12 approved these changes
It looks like everything is fine now.

2022-10-11 20:18 UTC, razvand approved these changes
All is good. Thanks, @RaduNichita , @mandrei12 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-10-11 20:19 UTC, merged