docs/develop: Add build and run complex apps doc
unikraft/docs pull request #147
Opened 2022-10-22 18:17 UTC by mariasfiraiala

This PR adds documentation for building and running complex applications on `x86` and `AArch64`.

It goes into detail regarding configuration steps and manual launch commands for the make build system.
Depends on having these PRs merged:

* [core Unikraft virtio PR](https://github.com/unikraft/unikraft/pull/519)
* [`newlib` PR](https://github.com/unikraft/lib-newlib/pull/21)

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-03-02 08:40 UTC, mariasfiraiala commented
With the transition to `musl` finally stable, I got the time to revisit this PR and finalize the documentation. @StefanJum @razvand please take a look when you have the time.

2023-03-02 15:01 UTC, StefanJum requested changes
Thanks a lot @mariasfiraiala, see my comments.

2023-03-02 15:01 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +1. choose all `Virtio` options from `Platform configuration`->`KVM guest`->`Virtio`
Shouldn't `musl` also be here?

2023-03-02 15:01 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +                  Phoebe 0.10.0~9bf6e63
Change this to the `0.12` unikraft version :rocket:

2023-03-03 18:53 UTC, mariasfiraiala commented
Done @StefanJum! Take another tour when you find the time.

2023-03-03 19:15 UTC, StefanJum requested changes
Looks really nice @mariasfiraiala, thank you.
I will test the command in the next few days and come back with a new round.

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +There are many to choose from, so you go for `app-sqlite`, `app-redis` or `app-nginx`.
```suggestion
There are many to choose from, so we will go for `app-sqlite`, `app-redis` or `app-nginx`.
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +This tutorial is here to guide you through the first steps towards successfully launching your (more complex) unikernel; we'll present 2 scenarios: building for `x86` and `AArch64`.
```suggestion
This tutorial is here to guide us through the first steps towards successfully launching our (more complex) unikernel; we'll present 2 scenarios: building for `x86` and `AArch64`.
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +The process of building `app-sqlite` for `AArch64` is quite similar to the one we've layed out for the `x86` architecture, the only thing that needs changes being the architecture, which should be sw
Maybe also specify that a properclean must be done after changing the architecture.

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +We should alos create a `Makefile.uk` in the `app-redis` directory:
```suggestion
We should also create a `Makefile.uk` in the `app-redis` directory:
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +With this last command, our tutorial ends here, it was a long ride but the results should be rewarding enough.
```suggestion
With this last command, our tutorial ends, it was a long ride but the results should be rewarding enough.
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +$ make
```suggestion
$ make -j $(ncpus)
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +$ make
```suggestion
$ make -j $(ncpus)
```

2023-03-03 19:15 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +$ make
```suggestion
$ make -j $(ncpus)
```

2023-03-03 19:44 UTC, mariasfiraiala commented
Great thing @StefanJum. I've also integrated your latest suggestions. Hope it looks alright now (Markdown wise).

2023-03-08 09:29 UTC, StefanJum requested changes
Great work @mariasfiraiala, I tested the commands and everything works well.
See the few comments I left.

2023-03-08 09:29 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +1. Choose the `Redis`, `lwip`, `musl` libraries from `Library Configuration`
```suggestion
1. Choose the `Redis`, `lwip` and `musl` libraries from `Library Configuration`
```

2023-03-08 09:29 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +
As on the `sqlite` app, mention that a `properclean` is needed here.

2023-03-08 09:29 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +LIBS := $(UK_LIBS)/lib-musl:$(UK_LIBS)/lib-lwip:$(UK_LIBS)/lib-redis
```suggestion
LIBS := $(UK_LIBS)/lib-musl:$(UK_LIBS)/lib-lwip:$(UK_LIBS)/lib-nginx
```

2023-03-08 09:29 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +
As on the `sqlite` app, mention that a `properclean` is needed here.

2023-03-11 09:13 UTC, mariasfiraiala commented
I've committed your suggestions @StefanJum. Take another look!

2023-03-11 09:41 UTC, StefanJum requested changes
All good besides the few comments, thanks @mariasfiraiala.
@razvand please take a quick look over this.

2023-03-11 09:41 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +We should be left with a file hierarchy that should look like this:
```suggestion
We should be left with a file hierarchy that looks like this:
```

2023-03-11 09:41 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +We should be left with a file hierarchy that should look like this:
```suggestion
We should be left with a file hierarchy that looks like this:
```

2023-03-11 09:41 UTC, StefanJum commented on content/en/docs/usage/make_build.md
> +We should be left with a file hierarchy that should look like this:
```suggestion
We should be left with a file hierarchy that looks like this:
```

2023-03-11 11:13 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-03-22 17:34 UTC, razvand requested changes
Hi, @mariasfiraiala. This looks very good. See my minor comments.

I want to take another tour, to test the steps you mentioned and make sure everything is clear for future readers.

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +For every application, we'll present 2 scenarios: building for `x86` and `AArch64`.
```suggestion
For every application, we'll present 2 scenarios: building for `x86_64` and `AArch64`.
```

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +### `app-sqlite` for `x86`
```suggestion
### `app-sqlite` for `x86_64`
```

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +This way, it's easier to type it, but if you fancy even more automation, check out [`qemu-guest`](https://github.com/unikraft/kraft/blob/staging/scripts/qemu-guest) or even [`kraft`](https://unikraft
```suggestion
This way, it's easier to type it, but if you fancy even more automation, check out [`qemu-guest`](https://github.com/unikraft/kraft/blob/staging/scripts/qemu-guest) or [`kraft`](https://unikraft.org/docs/usage/init/#kraft-run).
```

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +The process of building `app-sqlite` for `AArch64` is quite similar to the one we've layed out for the `x86` architecture, the only thing that needs changes being the architecture, which should be sw
Remind that configuration happens with `make menuconfig`.

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +1. Under the `vfscore` library, choose the `Default root filesystem` to be `9pfs`
```suggestion
1. Under the `vfscore` library, choose the `Default root filesystem` to be `9pfs`.
```

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +1. Choose the `x86` architecture from `Architecture Selection`
Add dots at the end.

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +For testing our app we'll open a new terminal, or use `tmux`, and give this command to retrive data from the server
```suggestion
For testing our app, we'll open a new terminal, or use `tmux`, and give this command to retrive data from the server:
```

2023-03-22 17:34 UTC, razvand commented on content/en/docs/usage/make_build.md
> +Just like we've stated for `SQLite` and `Redis`, for `AArch64` the build steps follow the tutorial for `x86`, the only thing that needs changes being the architecture, which should be switched to `Ar
```suggestion
Just like we've stated for `SQLite` and `Redis`, for `AArch64` the build steps follow the tutorial for `x86_64`.
The only thing that needs changes being the architecture, which should be switched to `Armv8` in the `Architecture Selection` menu.
```

2023-03-23 10:07 UTC, mariasfiraiala commented
Done @razvand. Take another look, please.

2023-04-18 12:33 UTC, razvand requested changes
Hi, @mariasfiraiala, see my comments. Also use `virbr0` as the bridge ID, instead of `kraft0`, throughout the tutorial.

2023-04-18 12:56 UTC, mariasfiraiala commented on content/en/docs/usage/make_build.md
> +
Not really, since we already provide it in the [app repo](https://github.com/unikraft/app-nginx).

2023-04-18 13:04 UTC, mariasfiraiala commented
Just integrated what you've suggested @razvand! Thanks for the time and take another look, please!

2023-04-18 13:34 UTC, razvand approved these changes
Thanks, @mariasfiraiala.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-04-18 13:34 UTC, merged