hack/munich22: Detail challenge types
unikraft/docs pull request #148
Opened 2022-10-23 08:17 UTC by razvand

Detail challenge types for Munich hackathon (October 22-23, 2022).

2022-10-23 08:52 UTC, RaduNichita requested changes

2022-10-23 08:52 UTC, RaduNichita commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +1. **Building applications as static PIE binaries** and adding the to the [`static-pie-apps` repository](https://github.com/unikraft/static-pie-apps)
```suggestion
1. **Building applications as static PIE binaries** and adding it to the [`static-pie-apps` repository](https://github.com/unikraft/static-pie-apps)
```

2022-10-23 08:52 UTC, RaduNichita commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +   These applications needn't run on Unikraft.
```suggestion
   These applications don't have to run on Unikraft.
```

2022-10-23 08:52 UTC, RaduNichita commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +   5-10 hackathon points are awarded for each fix.
```suggestion
   5-10 hackathon points are awarded for each fix. depending on its complexity.
```

2022-10-23 08:55 UTC, RaduNichita requested changes

2022-10-23 08:55 UTC, RaduNichita commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +Challenge types generally fall in the categories below.
```suggestion
Challenge types generally fall into the categories below.
```

2022-10-23 10:49 UTC, razvand commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +   5-10 hackathon points are awarded for each fix.
It's implied.

2022-10-23 11:08 UTC, RaduNichita approved these changes
All good now. Thanks for the great help, @razvand

Reviewed-by: Radu Nichita [radunichita99@gmail.com](mailto:radunichita99@gmail.com)

2022-10-23 14:26 UTC, StefanJum reviewed
Looks good, only one comment @razvand.
I will merge after that.

2022-10-23 14:26 UTC, StefanJum commented on content/en/community/hackathons/2022-10-munich/challenges/index.md
> +   These applications aren't require to run on Unikraft.
```suggestion
   These applications aren't required to run on Unikraft.
```

2022-12-11 16:38 UTC, razvand commented
> Looks good, only one comment @razvand. I will merge after that.

@StefanJum , solved

2022-12-11 18:24 UTC, StefanJum approved these changes
All good, thanks @razvand.

Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-12-11 18:25 UTC, merged