hack/munich22: Add blogpost for Munich hackathon
unikraft/docs pull request #151
Opened 2022-10-26 01:06 UTC by RaduNichita

Signed-off-by: Radu Nichita <radunichita99@gmail.com>

2022-11-04 06:57 UTC, razvand requested changes
@RaduNichita , see my requests.

2022-11-04 06:57 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +The participants seemed excited about the topics and dove deep into understanding the principles behind the unikernels. They were also very active in reporting some new issues.
```suggestion
The participants were given initial information about the topics and then they dove deep into understanding the principles behind the unikernels.
They were very active in reporting new issues.
```

2022-11-04 06:57 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +The second day started with Răzvan's spectacular presentation about `Binary Compatibility`.
```suggestion
The second day started with Răzvan's talk and demo on `Binary Compatibility`.
```

2022-11-04 06:57 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +The results were quite impressive, with 8 PRs submitted during the day.
```suggestion
Results speak for themselves:

 - 6 PRs submitted as part of the [`static-pie-apps` repository](https://github.com/unikraft/static-pie-apps/pulls)
 - PR for [version bump of `newlib`](https://github.com/unikraft/lib-newlib/pull/27)
 - PR for (version bump of `zlib`](https://github.com/unikraft/lib-zlib/pull/4)
 - 2 issues in the [core `unikraft` repository](https://github.com/unikraft/unikraft/issues)
 
 All contributions were awarded points that made it to [the scoreboard](https://leaderboardhq.com/3wt61mcc).
```

2022-11-04 06:57 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +Then, the folks got involved in solving hackathon challenges, from porting applications as `static-pie-apps` to fixing some existing issues).
```suggestion
Then, the folks created teams of 3-4 people, got an entry for each team in [the scoreboard](https://leaderboardhq.com/3wt61mcc) then then started solving [hackathon challenges](https://unikraft.org/community/hackathons/2022-10-munich/challenges/).
```

2022-11-04 06:57 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +
```suggestion
```

2022-11-06 10:54 UTC, razvand requested changes
Thanks, @RaduNichita . See my comments. After these are handled, we are ready to approve and publish the PR.

Make sure you spell checked the contents.

2022-11-06 10:54 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +It was the 3rd international onsite hackathon, after the ones in Lyon and Aachen.
```suggestion
It was the 3rd international onsite hackathon, after the ones in [Lyon](community/hackathons/2022-05-lyon/) and [Aachen](community/hackathons/2022-06-aachen/).
```

2022-11-06 10:54 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +From the Unikraft community, [Răzvan](https://github.com/razvand/) and [Radu](https://github.com/RaduNichita/) were there, whereas other community members provided support online, on Discord.
```suggestion
From the Unikraft community, [Răzvan](https://github.com/razvand/) and [Radu](https://github.com/RaduNichita/) were there, whereas other community members provided support online, on Discord (special thanks to [Ștefan](https://github.com/StefanJum).
```

2022-11-06 10:54 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +Over `30` participants came to Technische Universität München for the 2-day event about unikernels. This is the highest attendance for an onsite Unikraft Hackathon event!
```suggestion
Over `30` participants came to Technische Universität München for the 2-day event about unikernels.
This is the highest attendance for an onsite Unikraft Hackathon event!
```

2022-11-06 10:54 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +### Make open-source contributions great again!
```suggestion
### Make Open Source Contributions Great Again!
```

2022-11-06 10:54 UTC, razvand commented on content/en/blog/2022-10-25-unikraft-munich-2022.md
> +### Special thanks
```suggestion
### Special Thanks
```

2022-11-07 01:36 UTC, RaduNichita commented
> Thanks, @RaduNichita . See my comments. After these are handled, we are ready to approve and publish the PR.
> 
> Make sure you spell checked the contents.

I've used Grammarly for the spell check. Hope everything is OK now.

2022-11-07 04:39 UTC, razvand approved these changes
Thanks, @RaduNichita 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-11-07 04:40 UTC, merged