booting.md: Fix x86_64 boot explanation
unikraft/docs pull request #196
Opened 2023-03-09 14:00 UTC by gettsu

adapted the file and function names to the current repository

2023-03-09 18:22 UTC, StefanJum requested changes
Looks good @gettsu, besides the few comments, please also squash your commits.

2023-03-09 18:22 UTC, StefanJum commented on content/en/docs/develop/booting.md
> +All those are done in `plat/kvm/x86/lcp_start.S`.
```suggestion
All those are done in `plat/kvm/x86/lcpu_start.S`.
```

2023-03-09 18:22 UTC, StefanJum commented on content/en/docs/develop/booting.md
> +After that, interrupts, traps, the heap, the ACPI tables, and others, are initialized, in the `ukplat_entry` function, in `plat/kvm/x86/setup.c`.
```suggestion
After that, interrupts, traps, the heap, the ACPI tables, and others, are initialized, in the `_ukplat_entry` function, in `plat/kvm/x86/setup.c`.
```

2023-03-09 19:28 UTC, gettsu commented
Thanks for your comments !

2023-03-10 11:29 UTC, StefanJum requested changes
Looks better and better, thanks @gettsu.
Please sign-off your commit and add a short description on why the informations were outdated.

2023-03-11 07:49 UTC, StefanJum commented
@gettsu all looks good now, thanks a lot.
Please modify your commit message to fit to ~72 characters per line then we can merge this.

2023-03-11 09:26 UTC, gettsu commented
@StefanJum Thanks a lot! I just fixed it!

2023-03-11 09:42 UTC, StefanJum approved these changes
All good now, thanks @gettsu.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-03-11 09:43 UTC, merged