hack-athens23: Add guest talks
unikraft/docs pull request #208
Opened 2023-03-27 09:34 UTC by razvand

Add guest talks.

2023-03-27 09:48 UTC, razvand commented on content/en/community/hackathons/2023-03-athens/_index.md
> +| 16:45 - 17:15 | Unikernels for Serverless                                            | Anastassios Nanos  |
No, that's it.

2023-03-27 09:52 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-03-28 02:13 UTC, razvand commented
> Looks good. A few things that can be improved:
> 
>     * Prepend title with "Guest Talk: "
> 
>     * Add affiliation next to the speakers' names (Nubificus, NVIDIA, ...)
> 
>     * Fill in the Presenter field in the rest of the sessions.
> 
> 
> If you think these are unnecessary please feel free to merge as is; I have approved already slightly_smiling_face

@michpappas, done. Re-approve if OK, and then I'll publish the information.

2023-03-28 05:36 UTC, michpappas requested changes
IIRC Dimitris Syrivelis is from NVIDIA, not UoA: 
https://www.linkedin.com/in/dimitris-syrivelis-3208533
We can double-check with Anastassios if needed.

Other than that looks great 👍

2023-03-28 14:02 UTC, razvand commented
> IIRC Dimitris Syrivelis is from NVIDIA, not UoA: https://www.linkedin.com/in/dimitris-syrivelis-3208533 We can double-check with Anastassios if needed.
> 
> Other than that looks great +1

@michpappas, done. See if this is OK now.

2023-03-28 14:18 UTC, michpappas approved these changes
Looks good 👍🏼

2023-03-28 14:19 UTC, merged