blog: Add blog post for Arm CCA GSoc project
unikraft/docs pull request #264
Opened 2023-06-19 11:51 UTC by zhxj9823

2023-06-25 19:53 UTC, mariasfiraiala requested changes
Thanks @zhxj9823. This looks good! Please, take into consideration the comments below. This is the first round of the review, expect even more suggestions in the future :smile:

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +Arm CCA is a new confidential computing technology in Arm v9 architecture that enables OS to run as a confidential VM without trusting the underlying hypervisor.
```suggestion
Arm CCA is a new confidential computing technology in Armv9 architecture that enables OS to run as a confidential VM without trusting the underlying hypervisor.
```

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +Therefore, to use Unikraft as an application in a realm, it needs to support the use of RSI.
```suggestion
Therefore, to use a unikernel as an application in a realm, Unikraft needs to support the use of RSI.
```

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +On the information-gathering side, the following questions are answered:
Please, do not use passive voice for the work you accomplished. Always use the active voice. For example, "**I** answered the following questions", "**I** made some changes to the Unikraft core" etc.

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +On the code-implementation side, some changes are made to Unikraft to make `app-helloworld` run on kvmtool.
Use active voice

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- The mapping in kvmtool is different from qemu `virt`, so the page table in `unikraft/plat/kvm/arm/bpt64.S` is changed.
Use active voice

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- Kvmtool supports the ns16550 serial console instead of the default pl011 in Unikraft, so the pl011 console is replaced.
Use active voice

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +  So `_init_dtb_mem` is changed to avoid the overlapping of the heap and the dtb region.
Use active voice

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +As `app-helloworld` of Unikraft can be run in kvmtool and the relevant knowledge of CCA is gathered, this project moves toward adding support for CCA and running `app-helloworld` in a realm.
```suggestion
As  Unikraft's `app-helloworld` can be run in kvmtool and the relevant knowledge of CCA is gathered, this project moves toward adding support for CCA and running `app-helloworld` in a realm.
```

2023-06-25 19:53 UTC, mariasfiraiala commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +On the code-implementation side, some changes are made to Unikraft to make `app-helloworld` run on kvmtool.
It would be great if you could link the commits relevant to the work you're describing here, if you have any. Otherwise, this looks good.

2023-06-30 07:30 UTC, razvand requested changes
Nice work, @zhxj9823. Please see my comments.

Also squash the commits.

Generally look into the [contribution guidelines](https://unikraft.org/docs/contributing/submitting-changes/) and also see the [documentation on documentation](https://unikraft.org/docs/contributing/docs/).

2023-06-30 07:30 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +## About Me
Add links to your GitHub name and to the university website.

2023-06-30 07:30 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +Arm CCA introduces Realm Management Extension (RME), which extends Arm TrustZone technology with two new security states: the `realm` state and the `root` state.
Add links detailing RME and TrustZone.

2023-06-30 07:30 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +
Is `kvmtool` a command. If so, use backticks for it.

2023-07-02 12:59 UTC, razvand requested changes
@zhxj9823, see my comments. They're minor. After this is done, we can then merge the pull request.

Please prefer using `*` instead of `-` for unordered lists in GitHub Markdown.

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +[This project](https://summerofcode.withgoogle.com/programs/2023/projects/5oKH0o5n) aims to bring [Arm Confidential Computing Architecture (CCA)](https://www.arm.com/architecture/security-features/ar
```suggestion
[This project](https://summerofcode.withgoogle.com/programs/2023/projects/5oKH0o5n) aims to bring [Arm Confidential Computing Architecture (CCA)](https://www.arm.com/architecture/security-features/arm-confidential-compute-architecture) feature to Unikraft.
It has been accepted as a [Google Summer of Code (GSoC)](https://summerofcode.withgoogle.com/) project.
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +Arm CCA is a new confidential computing technology in Armv9 architecture that enables OS to run as a confidential VM without trusting the underlying hypervisor.
Link Armv9 architecture.

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +On the code-implementation side, the differences between kvmtool and qemu `virt` platforms lead to several changes:
```suggestion
On the code-implementation side, the differences between kvmtool and QEMU `virt` platforms lead to several changes:
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- Kvmtool supports the ns16550 serial console, so it replaces the default pl011 in Unikraft.
```suggestion
- Kvmtool supports the `ns16550` serial console, so it replaces the default `pl011` in Unikraft.
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +  Besides, the ns16550 serial console in kvmtool uses byte-width registers.
```suggestion
  Besides, the `ns16550` serial console in kvmtool uses byte-width registers.
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- Add support for kvmtool to run `app-helloworld` in the normal world.
```suggestion
- Add support for kvmtool to run [`app-helloworld`](https://github.com/unikraft/app-helloworld) in the normal world.
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +As  Unikraft's `app-helloworld` can be run in kvmtool and the relevant knowledge of CCA is gathered, this project moves toward adding support for CCA and running `app-helloworld` in a realm.
```suggestion
As Unikraft's `app-helloworld` can be run in kvmtool and the relevant knowledge of CCA is gathered, this project moves toward adding support for CCA and running `app-helloworld` in a realm.
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- What are the changes in the realm linux?
```suggestion
- What are the changes in the realm Linux?
```

2023-07-02 12:59 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-arm-cca-1.md
> +- How unikraft currently boots?
```suggestion
- How does Unikraft currently boot?
```

2023-07-10 14:39 UTC, razvand approved these changes
Thanks, @zhxj9823.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-10 14:45 UTC, merged