blog: Add a blog for GSoC'23: Binary Compatibility
unikraft/docs pull request #265
Opened 2023-06-19 18:03 UTC by i-Pear

2023-06-30 07:33 UTC, razvand requested changes
Thanks, @i-Pear, this looks great.

Please use "Add blog post" instead of "Add a blog" in the commit message. Also add a short summary paragraph detailing the blog post contents.

See the linter errors.

Generally look into the [contribution guidelines](https://unikraft.org/docs/contributing/submitting-changes/) and also see the [documentation on documentation](https://unikraft.org/docs/contributing/docs/).

2023-06-30 07:33 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-app-compat-1.md
> +## Next steps
```suggestion
## Next Steps
```

2023-06-30 07:33 UTC, razvand commented on content/en/blog/2023-06-23-unikraft-gsoc-app-compat-1.md
> +I'm Tianyi Liu, a first-year graduate student at Nanjing University.
Add links to your GitHub page and the university page.

2023-06-30 09:19 UTC, i-Pear commented
@razvand Thanks for you review, I have completed all the revisions.

2023-07-01 07:03 UTC, razvand requested changes
Hi, @i-Pear, please use your full name both for the commit author and for the signed off message.

Also add a paragraph description of the commit message. Something like:

"""
Part of the "Extending Binary Compatibility" GSoC'23 project, this blog post details work in first 3 weeks of GSoC, together with planned work for the upcoming 3 weeks.
"""

See my other comments inline.
```

2023-07-10 14:45 UTC, merged