hack-vancouver23: Add landing page
unikraft/docs pull request #267
Opened 2023-06-22 11:45 UTC by razvand

Add landing page for Vancouver Unikraft Hackathon, on September 23-24, 2023

2023-06-25 14:37 UTC, StefanJum requested changes
See the comments. It's all good besides that.

2023-06-25 14:37 UTC, StefanJum commented on content/en/community/hackathons/2023-09-vancouver/_index.md
> +| Time (CET)    | Session                                         |
Are the times CET or Vancouver local time?

2023-06-25 14:37 UTC, StefanJum commented on content/en/community/hackathons/2023-09-vancouver/_index.md
> +| Time (CET)    | Session                                             |
Are the times CET or Vancouver local time?

2023-06-26 14:40 UTC, razvand commented
@StefanJum , please see the updated version. Then we can merge it and start advertising.

2023-06-26 15:36 UTC, StefanJum reviewed
@razvand the links in the [registration form](https://forms.gle/mDumYG8pQtxcX3ES9) are marked as `TODO`s. We can publish and do the announcements after those are fixed.

2023-06-29 13:20 UTC, razvand commented
> @razvand the links in the [registration form](https://forms.gle/mDumYG8pQtxcX3ES9) are marked as `TODO`s. We can publish and do the announcements after those are fixed.

@StefanJum , fixed. Take another look please.

2023-06-29 13:26 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-06-29 13:26 UTC, merged