`docs/features`: Update security features page
unikraft/docs pull request #290
Opened 2023-07-12 14:01 UTC by razvand

Update security features page to the current state of things.

2023-07-12 14:05 UTC, michpappas approved these changes
Looks good 🚀 

Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2023-07-12 14:21 UTC, StefanJum requested changes
See the comments @razvand

2023-07-12 14:21 UTC, StefanJum commented on content/en/docs/features/security.md
>  | [Position Independent Executables (PIE)](https://github.com/unikraft/unikraft/pull/239)                | Under review     | `PLAT_KVM && ARCH_X86_64`      |
Also change this link to point to https://github.com/unikraft/unikraft/pull/772

2023-07-12 17:19 UTC, mariasfiraiala approved these changes
Besides @StefanJum's comments, this looks alright. Thanks @razvand!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-07-13 01:15 UTC, michpappas commented on content/en/docs/features/security.md
> +| Arm CCA (Confidential Compute Architecture)                                                            | In progress      | `ARCH_ARM_64` (Armv9)          |
A bit too draft to put on the front page IMO. It's just there to collect changes, but there will be individual PRs shortly.

2023-07-13 05:08 UTC, StefanJum commented on content/en/docs/features/security.md
> +| Arm CCA (Confidential Compute Architecture)                                                            | In progress      | `ARCH_ARM_64` (Armv9)          |
Ok, makes sense.

2023-10-06 12:43 UTC, StefanJum commented
Covered by the website refactoring.

2023-10-06 12:43 UTC, closed without merging