hack/usco23: Introduce section 05: Debugging
unikraft/docs pull request #291
Opened 2023-07-12 16:05 UTC by vladandrew

This pull request introduces the fifth session about debugging under Unikraft. This session goes over common debugging techniques and how we can use them on Unikraft.

2023-07-12 17:52 UTC, StefanJum requested changes
@vladandrew I know this is WIP, just a few comments.

2023-07-12 17:52 UTC, StefanJum commented on content/en/community/hackathons/usoc23/debugging/index.md
> +weight: 4
```suggestion
weight: 5
```

2023-07-12 17:52 UTC, StefanJum commented on content/en/community/hackathons/sessions/debugging/content/Debugging_Using-GDB.md
> +
```suggestion

```

2023-07-13 07:39 UTC, StefanJum commented on content/en/community/hackathons/usoc23/debugging/index.md
> +Thank you!
Remove this, it's for last year.

2023-07-13 09:22 UTC, StefanJum commented on content/en/community/hackathons/usoc23/debugging/index.md
> +### 05. Bad ELF in Town
@vladandrew Please also remove this, it's too much for the scope of the session

2023-07-13 09:35 UTC, vladandrew commented on content/en/community/hackathons/usoc23/debugging/index.md
> +{{< readfile file="/community/hackathons/sessions/debugging/content/Practical-Work_06.-Nginx-with-or-without-main?-That's-the-question..md" markdown="true" >}}
Done

2023-07-13 09:35 UTC, vladandrew commented on content/en/community/hackathons/usoc23/debugging/index.md
> +{{< readfile file="/community/hackathons/sessions/debugging/content/Practical-Work_01.-Tutorial.-Use-GDB-in-Unikraft.md" markdown="true" >}}
Done for all

2023-07-13 10:31 UTC, StefanJum requested changes
Just few more minor comments, we can merge it after that @vladandrew

2023-07-13 10:31 UTC, StefanJum commented on content/en/community/hackathons/sessions/debugging/content/Practical-Work_01.-Tutorial.-Use-GDB-in-Unikraft.md
>  ```
```suggestion
```text
```

2023-07-13 10:31 UTC, StefanJum commented on content/en/community/hackathons/sessions/debugging/content/Practical-Work_01.-Tutorial.-Use-GDB-in-Unikraft.md
> +
```suggestion
app-helloworld/
|-- Makefile
....
`-- .unikraft
    `-- unikraft
    `-- libs
        `-- lib-...

```
Use ascii output

2023-07-13 10:53 UTC, StefanJum approved these changes
All good now, thanks @vladandrew 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-13 10:53 UTC, merged