content/docs: Add FAQ content
unikraft/docs pull request #31
Opened 2022-02-05 15:39 UTC by cristian-vijelie

2022-02-05 18:11 UTC, razvand approved these changes
Very good. Thanks, @cristian-vijelie 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-02-06 13:55 UTC, nderjung requested changes
In the future it would be good to have a partial that styles the list nicely, e.g.:

```
{{< faq question="Why Unikraft and not a container?" >}}
Unikraft is faster and more lightweight...
{{</ faq >}}
```

For now this is fine.  Can you just change the A to indicate being faster than a container?

2022-02-06 13:55 UTC, nderjung commented on content/en/docs/faq.md
> +A: Unikraft is as fast and lightweight as a container, while having the security of a virtual machine.
faster* ;)

2022-02-07 06:12 UTC, cristian-vijelie commented
@nderjung done

2022-09-03 11:43 UTC, StefanJum commented
Thank you. This will be addresed by #109, the content there is taken from here.

2022-09-03 11:43 UTC, closed without merging