guides: Update bincompat
unikraft/docs pull request #367
Opened 2024-01-07 21:50 UTC by razvand

Update binary compatibility guide to focus on application `catalog`, KraftKit-based runs, the `base` kernel image and the application registry.

2024-01-28 20:01 UTC, paun75 approved these changes
Reviewed-by: Daniel Paun <paundani2001@gmail.com>

2024-01-29 09:12 UTC, StefanJum requested changes
The content looks good, but there are some rendering issues, see the comments.

2024-01-29 09:12 UTC, StefanJum commented on content/guides/catalog.mdx
Rename this file to something like `catalog-usage.mdx`, if you only use `catalog.mdx` it will be ignored in the render process for whatever reason, and the `guides/catalog` web page will point to `catalog-add.mdx`.

Also update the link in the  `bincompat.mdx` file after you update the name.

2024-01-30 22:45 UTC, Mihnea0Firoiu approved these changes
Looks good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2024-01-31 07:43 UTC, StefanJum approved these changes
All good now, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-02-02 08:15 UTC, nderjung approved these changes
Thanks a lot @razvand, this is very well written and put together, gg!

Reviewed-by: Alexander Jung <alex@unikraft.io>
Approved-by: Alexander Jung <alex@unikraft.io>

2024-02-02 08:15 UTC, merged