Add blog entry for lxboot x86
unikraft/docs pull request #429
Opened 2024-06-18 12:43 UTC by Mihnea0Firoiu

The first blog post for lxboot x86

2024-06-19 09:53 UTC, StefanJum requested changes

2024-06-19 09:53 UTC, StefanJum commented on content/blog/2024-06-18-gsoc-lxboot_x86.mdx
> +
```suggestion
In particular, the Linux boot protocol greatly contributes to the overall robustness and reliability of the bootstrapping process on Linux-based systems.
Almost, if not all, widely available bootloaders that exist on the market are able to speak this protocol and Unikraft, being unable to be detected by these bootloaders as a Linux Boot Protocol compliant system, is hindering the ability of Unikraft to boot on a very large amount of platforms.

```
Please use one line per sentence and one sentence per line

2024-06-19 09:53 UTC, StefanJum commented on content/blog/2024-06-18-gsoc-lxboot_x86.mdx
> +Once everything works for QEMU, I will move onto GRUB2 and look into making lxboot x86 work with it as ISO and as Disk.
Try to add a few more detailed steps on what needs to happen in order for this to run on `qemu`. What the `mklinux_x86.py` script will contain, what the header of the image will look like, etc.

2024-06-19 16:27 UTC, mogasergiu approved these changes
Other than what @StefanJum said, LGTM.

2024-06-20 07:47 UTC, StefanJum requested changes
Few more comments.

2024-06-20 07:47 UTC, StefanJum commented on content/blog/2024-06-18-unikraft-gsoc-lxboot_x86.mdx
> +One difference between two different boot loaders is that some have an identifier.
This sentence is a bit confusing. Would something like "Boot loaders have unique reserved identifiers, placed in the `type_of_loader` field" make more sense?

2024-06-20 07:47 UTC, StefanJum commented on content/blog/2024-06-18-unikraft-gsoc-lxboot_x86.mdx
> +At the moment, I am looking into creating `support/scripts/mklinux_x86.py` using as inspiration the already existing `mklinux.py` and the [ARM64 PR](https://github.com/unikraft/unikraft/pull/988).
```suggestion
At the moment, I am looking into creating `support/scripts/mklinux_x86.py` using as inspiration the already existing [`mklinux.py`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/mklinux.py) and the [ARM64 PR](https://github.com/unikraft/unikraft/pull/988).
```

2024-06-20 07:47 UTC, StefanJum commented on content/blog/2024-06-18-unikraft-gsoc-lxboot_x86.mdx
> +Almost, if not all, widely available bootloaders that exist on the market are able to speak this protocol and Unikraft, being unable to be detected by these bootloaders as a Linux Boot Protocol compl
```suggestion
Almost, if not all, widely available bootloaders that exist on the market are able to speak this protocol and Unikraft, being unable to be detected by these bootloaders as a Linux Boot Protocol compliant system, is hindering the ability to boot on a very large amount of platforms.
```

2024-06-20 14:41 UTC, StefanJum approved these changes
Looks good now, thanks.

2024-06-21 12:27 UTC, merged