content/blog: Add second GSoC blog post about Multiboot2
unikraft/docs pull request #439
Opened 2024-07-09 18:40 UTC by mariapana

Added the second GSoC blog post about Multiboot2 showcasing the progress made during the second set of 3 weeks.

Signed-off-by: Maria Pana <maria.pana4@gmail.com>

2024-07-10 09:05 UTC, cristian-vijelie commented on content/blog/2024-07-10-gsoc-multiboot2.mdx
> +It then loads the kernel into memory, sets up the environment, and transfers control to the kernel's entry point.
I would say here that the bootloader, after finding the information requested by the tags in the header, places that information in the kernel memory, then passes the control, for clarity

2024-07-12 09:14 UTC, StefanJum commented
@mariapana please squash the commits. Otherwise looks fine.
@cristian-vijelie @mogasergiu after you take a look at it content-wise, we can merge.

2024-07-12 13:27 UTC, mogasergiu requested changes
Looks good! :+1: A couple of minor comments.

2024-07-12 13:27 UTC, mogasergiu commented on content/blog/2024-07-10-gsoc-multiboot2.mdx
> +On top of that, both `multiboot.py` and `multiboot2.py` scripts add an extra ELF header, "sandwiching" the Multiboot2 header between it and the original ELF.
> As discussed, you will probably still have to duplicate (and update) the 64-bit ELF headers.

Ah you mention it here as well, yeah, ok so then I would update what is said above as well I guess?
(also "sandwiching" :eye: :sandwich: :+1: )

2024-07-12 17:27 UTC, mogasergiu approved these changes
LGTM.

Reviewed- by: Sergiu Moga <sergiu@unikraft.io>

2024-07-13 08:18 UTC, cristian-vijelie approved these changes

2024-07-13 11:52 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-07-13 11:53 UTC, merged