blog: Add GSoC'24 UEFI GOP, Part III Post
unikraft/docs pull request #450
Opened 2024-08-07 16:22 UTC by procub3r

2024-08-07 16:47 UTC, procub3r commented
Fixed all linter issues.

2024-08-08 17:43 UTC, StefanJum requested changes
@procub3r please use your full name for the signoff, commiter and author fields.

```
Author: procub3r <procub3r@proton.me>
Commit: procub3r <procub3r@proton.me>

    blog: Add GSoC'24 UEFI GOP, Part III Post
    
    Signed-off-by: procub3r <procub3r@proton.me>
```

Use `git config --global user.name` and then amend the commit.

2024-08-08 17:43 UTC, StefanJum commented on content/blog/2024-08-07-gsoc-uefi-gop.mdx
> +All of my work has been rebased onto the work done in `PR #1464`.
link the pr

2024-08-08 17:44 UTC, StefanJum commented
Also @mogasergiu please take a quick look.

2024-08-09 08:03 UTC, mogasergiu approved these changes
Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

2024-08-11 11:02 UTC, procub3r commented on content/blog/2024-08-07-gsoc-uefi-gop.mdx
> +All of my work has been rebased onto the work done in `PR #1464`.
linked :+1:

2024-08-11 11:10 UTC, StefanJum commented
@procub3r the author name and email is still wrong
```
Author: procub3r <procub3r@proton.me>
Commit: Sriprad Potukuchi <sripradp@proton.me>

    blog: Add GSoC'24 UEFI GOP, Part III Post
    
    Signed-off-by: Sriprad Potukuchi <sripradp@proton.me>
```

2024-08-11 11:19 UTC, procub3r commented
@StefanJum Fixed now. Didn't know I had to change that separately :sweat_smile:

2024-08-11 11:24 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-08-11 11:24 UTC, merged