Add Makefile build to Getting Started
unikraft/docs pull request #78
Opened 2022-06-30 11:41 UTC by marcrittinghaus

The current Getting Started page only describes how to setup and build Unikraft with `kraft`. However, sometimes it makes sense to work with a `Makefile` directly. This commit adds a description on how to do this.

2022-07-03 06:35 UTC, StefanJum requested changes
This is a great addition.
Except for the few broken links, all looks good.

2022-07-03 06:35 UTC, StefanJum commented on content/en/docs/getting-started/_index.md
> +As an alternative to `kraft` it is also possible to build Unikraft using a regular [`Makefile`](#building-unikraft-via-makefile).
```suggestion
As an alternative to `kraft` it is also possible to build Unikraft using a regular [`Makefile`](docs/getting-started/#building-unikraft-via-makefile).
```

2022-07-03 06:35 UTC, StefanJum commented on content/en/docs/getting-started/_index.md
> +See [here](../operations/plats/kvm.md) for further information on running the unikernel with KVM.
```suggestion
See [here](docs/operations/plats/kvm) for further information on running the unikernel with KVM.
```

2022-07-25 05:56 UTC, marcrittinghaus commented
> This is a great addition. Except for the few broken links, all looks good.

Thanks for catching these errors @StefanJum! I have fixed them as you suggested.

2022-07-25 08:13 UTC, StefanJum commented
> > This is a great addition. Except for the few broken links, all looks good.
> 
> Thanks for catching these errors @StefanJum! I have fixed them as you suggested.

Hi @marcrittinghaus, I think you forgot to add the file to the commit, the links did not change :)

2022-07-25 09:46 UTC, marcrittinghaus commented
> Hi @marcrittinghaus, I think you forgot to add the file to the commit, the links did not change :)

Sorry! :neutral_face: This is the git version of forgetting the attachment in an email 🤦🏻‍♂️

2022-07-25 10:45 UTC, StefanJum approved these changes
All good now.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-08-30 15:40 UTC, merged